<html>
<head>
    <title><?php echo $data['pageTitle'];?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/app.main.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Proza+Libre" rel="stylesheet">
</head>
<body>
<header>
    <div class="container row">
        <div class="col-sm-4">
            <a href="/">Logo</a>
        </div>
        <div class="col-sm-8">
            <nav class="row text-center">
                <div class="col">
                    <a href="/hobbies">Hobbies</a>
                </div>
                <div class="col">
                    <a href="/growing-up">Growing Up</a>
                </div>
                <div class="col">
                    <a href="/barkbook">Barkbook</a>
                </div>
                <div class="col">
                    <a href="/gallery">Gallery</a>
                </div>
                <div class="col">
                    <a href="/contact">Contact</a>
                </div>
            </nav>
        </div>
    </div>
</header>