<html>
<head>
    <title><?php echo $data['pageTitle'];?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/app.main.min.css">
</head>
<body>
<header>
    <nav class="row">
        <div class="col-sm-4">
            left 1/3
        </div>
        <div class="col-sm-4">
            middle 1/3
        </div>
        <div class="col-sm-4">
            right 1/3
        </div>
    </nav>
</header>