<html>
<head>
    <title><?php echo $data['pageTitle'];?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/app.main.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Proza+Libre" rel="stylesheet">
</head>
<body>
<header>
    <nav class="row text-center">
        <div class="col">
            <a href="/">Home</a>
        </div>
        <div class="col">
            <a href="/about">About Zero</a>
        </div>
        <div class="col">
            <a href="/contact">Contact Us</a>
        </div>
    </nav>
</header>