<footer class="container row">
    <div class="col-sm-12 col-md-4">
    </div>
    <div class="col-sm-12 col-md-4 text-center">
    </div>
    <div class="col-sm-12 col-md-4 text-right">
        <h4 id="footer-social-title">Say 'Woof':</h4>
        <a href="https://www.facebook.com/" target="_blank">
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
        </a>
        <a href="https://plus.google.com/" target="_blank">
            <i class="fa fa-google-plus-square" aria-hidden="true"></i>
        </a>
        <a href="https://www.pinterest.com/" target="_blank">
            <i class="fa fa-pinterest-square" aria-hidden="true"></i>
        </a>
        <a href="https://twitter.com/" target="_blank">
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
        </a>
    </div>
</footer>
<script type="text/javascript" src="//use.fontawesome.com/7d24f02257.js"></script>
<script type="text/javascript" src="/public/app.base.min.js"></script>
<script type="text/javascript" src="/public/app.main.min.js"></script>
</body>
</html>