<?php
$barkbookData = [
    'name'=>'Kaycee',
    'age'=>'2.5 Years Old',
    'breed'=>'Golden Retriever',
    'friendship'=>'Tom and Jerry',
    'image'=>''
];

include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <?php include_once('partials/template.phtml');?>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');