<?php
$barkbookData = [
    'name'=>'Kaycee',
    'age'=>'2.5 Years Old',
    'breed'=>'Golden Retriever',
    'friendship'=>'Tom and Jerry',
    'image'=>'kaycee.jpg'
];

include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <?php include_once('partials/sidebar.phtml');?>
            <div class="col-sm-8">
                <p>
                    Kaycee has gotten quite big now, as can be seen in the background of the video about <a class="text-decoration" href="/favourites/toys">Zero's toys</a>
                </p>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');