<?php include_once($data['viewsDirectory'].'helpers/helpers.php');
include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <?php include_once('partials/sidebar.phtml');?>
            <div class="col-sm-12 col-md-8">
                <p>
                    Wrigley is the matriarch of the family's dogs as she is the oldest and most elegant.  Zero first met Wrigley when he was 7 months old.  Zero really liked Wrigley but she was not as keen about him.  After this photo Zero wanted to play but Wrigley just went and took a nap.
                </p>
                <img class="body-image" src="<?php echo $data['imagesDirectory'];?>barkbook/zero-wrigley.jpg" alt="Zero and Wrigley"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');