<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lorem metus, commodo eget ligula vitae, malesuada rhoncus ex. Nullam sem lorem, varius in hendrerit vel, aliquam sit amet augue. Sed at euismod eros, nec iaculis magna. Ut pulvinar ante est. Pellentesque ac tempus justo. Pellentesque elit tellus, viverra eu risus congue, aliquam sollicitudin nibh. Aliquam ac porta sem. In tristique nulla ultricies lectus efficitur, eget vestibulum sem molestie.
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');