<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>Fetch</h3>
                <p>
                    tennis ball
                </p>
                <h3>Tricks</h3>
                <p>
                    video at christmas
                </p>
                <h3>Driving</h3>
                <p>
                    picture in sam's car
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');