<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-left-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>Toronto</h3>
                <p>
                    birth
                </p>
                <h3>Wisconsin</h3>
                <p>
                    lake
                </p>
                <h3>North Carolina</h3>
                <p>
                    farm
                </p>
                <h3>Dublin</h3>
                <p>
                    couch
                </p>
            </div>
            <div class="col-sm-3 position-relative hide-for-small">
                <img class="sidebar-image favourites-sidebar-right-image" src="<?php echo $data['imagesDirectory'].'barkbook/kaycee.jpg';?>"/>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');