<?php include_once($data['viewsDirectory'].'partials/header.phtml'); ?>
    <main class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title"><?php echo $data['pageTitle'];?></h1>
                <a href="/growing-up/puppyhood">Puppyhood</a>
                <a href="/growing-up/adolescence">Adolescence</a>
                <a href="/growing-up/adulthood">Adulthood</a>
            </div>
        </div>
    </main>
<?php include_once($data['viewsDirectory'].'partials/footer.phtml');